name: SurvivalGames
author: Zeao
description: The Main SurvivalGames plugin, the official and soon may be bug free.
main: Zeao\Main
version: 1.0.0
api: [3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
LOAD: STARTUP

commands:
    sg:
        description: SurvivalGames main command. 
